### ISSUE TITLE
Not able to karma start or run test

### ISSUE THREAD

**Issue by abadri** [pretenderjs/FakeXMLHttpRequest#57]
I am trying to do below steps and not able to start, below has the steps

1. `git clone https://github.com/pretenderjs/FakeXMLHttpRequest.git`
2. `npm install`
3. `karma start`

Error:
```bash
08 03 2021 12:17:36.694:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "framework:qunit"! (Resolving: framework:qunit)

```
or

` npm test`

```bash
FakeXMLHttpRequest git:(master) ✗ npm test

> fake-xml-http-request@2.1.1 test
> esperanto -i src/fake-xml-http-request.js -t umd -b -n FakeXMLHttpRequest -o fake_xml_http_request.js && ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS

fs.js:52
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:52:5
    at req_ (/Users/abadri/workspace/FakeXMLHttpRequest/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/abadri/workspace/FakeXMLHttpRequest/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/abadri/workspace/FakeXMLHttpRequest/node_modules/sander/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
npm ERR! code 1
npm ERR! path /Users/abadri/workspace/FakeXMLHttpRequest
npm ERR! command failed
npm ERR! command sh -c esperanto -i src/fake-xml-http-request.js -t umd -b -n FakeXMLHttpRequest -o fake_xml_http_request.js && ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abadri/.npm/_logs/2021-03-08T20_22_11_921Z-debug.log
```

```bash
➜  workspace git clone https://github.com/pretenderjs/FakeXMLHttpRequest.git
Cloning into 'FakeXMLHttpRequest'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 406 (delta 2), reused 0 (delta 0), pack-reused 400
Receiving objects: 100% (406/406), 249.39 KiB | 1.35 MiB/s, done.
Resolving deltas: 100% (212/212), done.
➜  workspace cd FakeXMLHttpRequest
➜  FakeXMLHttpRequest git:(master) npm install

added 282 packages, and audited 283 packages in 5s

40 vulnerabilities (17 low, 5 moderate, 18 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
➜  FakeXMLHttpRequest git:(master) ✗ karma start
zsh: command not found: karma
➜  FakeXMLHttpRequest git:(master) ✗ npm install -g karma

added 130 packages, and audited 131 packages in 3s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  FakeXMLHttpRequest git:(master) ✗ karma start
08 03 2021 12:17:36.694:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "framework:qunit"! (Resolving: framework:qunit)
➜  FakeXMLHttpRequest git:(master) ✗
```

**Comment by rwjblue** [comment]
What Node version were you testing on? Our CI here runs in Node 4 at the moment (:scream), you might need to use an older version until we update our graceful-fs version. Try with Node 10 or Node 12.
